### ISSUE TITLE
bug: all slash commands being registered on bot start

### ISSUE THREAD

**Issue by Miqhtiedev** [Geoxor/Sakuria#33]
every time you restart you register all the commands even if they have already been registered in a previous instance of the bot leading to the bot commands showing up twice or however many times the bot has been restarted.

![](https://i.imgur.com/uqWVFyS.png)

**Comment by Geoxor** [comment]
that is normal, the reason that happens is because half of them are global commands (they propegate after an hour or so) where as the updated ones are guild ones, after an hour you will see that they all will become the same, if theres a better way around this then we should implement it but this only affects dev guilds so
